project:
  type: book
  output-dir: _book

execute:
  freeze: auto

book:
  title: "Land in the Earth System 2 - Course information"
  subtitle: "Introducing global patterns, processes, and underlying principles for how climate shapes the terrestrial biosphere and how land feeds back to Earth system dynamics."
  author: "Benjamin Stocker, Laura Marqués, and Fabrice Lacroix"
  date: "13 September 2024"
  page-navigation: true
  chapters:
    - index.qmd
    - logistics.qmd
    - plan.qmd
    - assignments.qmd
  favicon: "figures/favicon.ico"
  twitter-card: true
  search: true
  repo-url: https://github.com/geco-bern/les2_course
  sharing: [twitter, facebook]
  navbar:
    title: " "
    logo: "images/logo.png"
    background: "#3A3A3A"
    search: true
    right:
      - text: "Home"
        file: index.qmd

bibliography: references.bib

format:
  html:
    theme: 
      light: [cosmo, theme-light.scss]
      dark: [cosmo, theme-dark.scss]
